language: java
jdk: oraclejdk8

# docker, see: https://docs.travis-ci.com/user/reference/overview/
#sudo: false
# Chrome no longer starts on the docker travis instance (Jan 2018)
# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
dist: trusty

addons:
  firefox: latest
  chrome: stable

install: true # disable default mvn install

notifications:
  slack: qaengineering:eTRqy0JhQOUtKHNO8mKLc8NC

env:
  global:
    # - CAPTURE_URL="https://localhost:5000" # disabled until new instance is available
    # - SUT_NAME="frameworkium"
    # - SUT_VERSION=${TRAVIS_BRANCH}
    - THREAD_COUNT=2
    - SELENIUM_MAJ_VER=3.8
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.1
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - GECKO_VER=0.19.1
    - CHROME_DRIVER_VER=2.34
    # override Travis default to give browsers more room
    - _JAVA_OPTIONS="-Xmx1024m -Xms128m"

before_script:
  # Set up Selenium Grid Hub
  - wget --quiet https://selenium-release.storage.googleapis.com/${SELENIUM_MAJ_VER}/${SELENIUM_JAR}
  - java -Xmx128m -jar ${SELENIUM_JAR} -role hub > /dev/null 2>&1 &

  # Download geckodriver
  - wget --quiet https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz
  - tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz

  # Download chromedriver
  - wget --quiet http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VER}/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip

  # Wait for grid hub to be up
  - until $(curl --output /dev/null --silent --fail http://localhost:4444/grid/console); do printf '.'; sleep 1; done

  # Setup Firefox Selenium Grid Node
  - java -Xmx128m -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=firefox,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5555 > /dev/null 2>&1 &

  # Set up Chrome Selenium Grid Node
  - java -Xmx128m -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=chrome,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5556 > /dev/null 2>&1 &

script:
  # Download deps, compile and run checkstyle
  - mvn install -B --quiet --show-version -DskipTests=true -Dmaven.javadoc.skip=true

  # Firefox on the grid
  - mvn verify -B -Dthreads=${THREAD_COUNT} -Dconfig=FirefoxGrid.yaml -DreuseBrowser=true -Dheadless=true

  # Firefox off the grid
  - mvn verify -B -Dthreads=${THREAD_COUNT} -Dbrowser=firefox -DreuseBrowser=true -Dheadless=true 2> /dev/null

  # Chrome on the grid
  - mvn verify -B -Dthreads=${THREAD_COUNT} -Dbrowser=chrome -DreuseBrowser=true -Dheadless=true -DgridURL=http://localhost:4444/wd/hub #-DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Query Jira for which test to run and then log results to Jira
  - mvn verify -B -Dbrowser=chrome -Dheadless=true -DgridURL=http://localhost:4444/wd/hub -DjiraURL="http://52.29.130.45:8080" -DjqlQuery="issueKey=TEST-1" -DresultVersion="BUILD TEST VERSION" -DzapiCycleRegex="Test Cycle" -DjiraUsername=frameworkium -DjiraPassword=frameworkium

  # SauceLabs- disabled until we have a sauce account to use
  # - mvn verify -Dsauce=true -Dplatform=ios -Dbrowser=safari -DplatformVersion=8.0 -Ddevice=iPad -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Allure report
  - mvn site -B --quiet
